language: go
dist: bionic

go:
  - 1.x

install:
  - sudo apt-get install clamav-daemon clamav-freshclam clamav-unofficial-sigs tree
  - sudo service clamav-freshclam stop
  - sudo freshclam --verbose
  - sudo service clamav-daemon start
  - RETRY_MAX=10; for i in $(seq 1 ${RETRY_MAX}); do [ -e /var/run/clamav/clamd.ctl ] && { break; }; sleep $((10 * $i)); done
  - sudo service clamav-daemon status
  - sudo tree /var/run/clamav

script:
  go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
