language: go
dist: bionic

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

install:
  - make get-deps
  - sudo apt-get install clamav-daemon clamav-freshclam clamav-unofficial-sigs tree
  - sudo service clamav-freshclam stop
  - sudo freshclam --verbose
  - sudo service clamav-daemon start
  - RETRY_MAX=10; for i in $(seq 1 ${RETRY_MAX}); do [ -e /var/run/clamav/clamd.ctl ] && { break; }; sleep $((10 * $i)); done
  - sudo service clamav-daemon status
  - sudo tree /var/run/clamav

script:
  go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
